routes/admin.php
<?php

/**
 * Admin Routes
 */
Route::prefix('admin')->group(function(){

  /**
  * Public Routes
  */
  Route::middleware('guest.admin')->group(function(){
    // Login
    Route::name('admin.session.login')->get('/acessar', 'Admin\Session\SessionController@showLoginForm');
    Route::name('admin.session.login')->post('/acessar', 'Admin\Session\SessionController@login');
    Route::name('autologin')->get('/autologin/{token}', '\Watson\Autologin\AutologinController@autologin');

    // Social Login
    Route::name('admin.social.redirect')->get('/social/redirect/{provider}', 'Admin\Session\SocialController@redirectToProvider');
    Route::name('admin.social.handle')->get('/social/handle/{provider}', 'Admin\Session\SocialController@handleProviderCallback');

    // Reset Password
    Route::name('admin.password.forgot')->get('/esqueci-minha-senha', 'Admin\Session\ForgotPasswordController@showLinkRequestForm');
    Route::name('admin.password.processForgot')->post('/esqueci-minha-senha', 'Admin\Session\ForgotPasswordController@sendResetLinkEmail');
    Route::name('admin.password.reset')->get('/cadastrar-senha/{token}', 'Admin\Session\ResetPasswordController@showResetForm');
    Route::name('admin.password.processReset')->post('/cadastrar-senha', 'Admin\Session\ResetPasswordController@reset');
  });

  // First access
  Route::name('admin.activation.create')->get('/primeiro-acesso', 'Admin\Session\ActivationController@showActivationForm');
  Route::name('admin.activation.processCreate')->post('/primeiro-acesso', 'Admin\Session\ActivationController@store');

  // Clients
  Route::name('admin.clients.welcome')->get('/bem-vindo/{id}', 'Admin\Clients\ClientController@welcome');

  /**
  * Protected Routes
  */
  Route::middleware(['auth.admin'])->group(function(){

    // Api Routes
    Route::prefix('api')->group(function(){
      // Media
      Route::prefix('media/images')->group(function(){
        Route::name('admin.media.index')->get('/', 'Api\MediaLibrary\MediaLibraryController@index');
        Route::name('admin.media.store')->post('/adicionar', 'Api\MediaLibrary\MediaLibraryController@store');
      });
    });

    // Logout
    Route::name('admin.session.logout')->get('/sair', 'Admin\Session\SessionController@logout');

    // Check first access
    Route::middleware(['first.access'])->namespace('Admin')->group(function() {

      // Dashboard
      Route::name('admin.dashboard.index')->get('/', 'Dashboard\DashboardController@index');

      // Account
      Route::prefix('perfil')->group(function() {
        Route::name('admin.accounts.show')->get('/', 'Users\AccountController@show');
        Route::name('admin.accounts.edit')->get('/atualizar', 'Users\AccountController@edit');
        Route::name('admin.accounts.update')->put('/atualizar', 'Users\AccountController@update');
      });

      // Orders
      Route::prefix('pedidos')->middleware('cors')->group(function() {
        Route::name('admin.orders.index')->get('/', 'Orders\OrderController@index');
      });

      // Releases
      Route::prefix('destaques')->group(function() {
        Route::name('admin.releases.index')->get('/', 'Releases\ReleaseController@index');
        Route::name('admin.releases.create')->get('/adicionar', 'Releases\ReleaseController@create');
        Route::name('admin.releases.store')->post('/adicionar', 'Releases\ReleaseController@store');
        Route::name('admin.releases.edit')->get('/editar/{id}', 'Releases\ReleaseController@edit');
        Route::name('admin.releases.update')->put('/editar/{id}', 'Releases\ReleaseController@update');
      });

      // Clients
      Route::prefix('clientes')->group(function() {
        Route::name('admin.clients.index')->get('/', 'Clients\ClientController@index');
        Route::name('admin.clients.show')->get('/visualizar/{id}', 'Clients\ClientController@show');
        Route::name('admin.clients.create')->get('/adicionar', 'Clients\ClientController@create');
        Route::name('admin.clients.store')->post('/adicionar', 'Clients\ClientController@store');
        Route::name('admin.clients.edit')->get('/editar/{id}', 'Clients\ClientController@edit');
        Route::name('admin.clients.update')->put('/editar/{id}', 'Clients\ClientController@update');
        Route::name('admin.clients.destroy')->delete('/deltar/{id}', 'Clients\ClientController@destroy');
      });

      // Promotions
      Route::prefix('promocoes')->group(function() {
        Route::name('admin.promotions.index')->get('/', 'Promotions\PromotionController@index');
        Route::name('admin.promotions.create')->get('/adicionar', 'Promotions\PromotionController@create');
        Route::name('admin.promotions.store')->post('/adicionar', 'Promotions\PromotionController@store');
        Route::name('admin.promotions.edit')->get('/editar/{id}', 'Promotions\PromotionController@edit');
        Route::name('admin.promotions.update')->put('/editar/{id}', 'Promotions\PromotionController@update');
        Route::name('admin.promotions.destroy')->delete('/excluir/{id}', 'Promotions\PromotionController@destroy');
        Route::name('admin.promotions.reorder')->post('/reordenar', 'Promotions\PromotionController@reorder');

        Route::prefix('categorias')->group(function() {
          Route::name('admin.promotions_categories.index')->get('/', 'Promotions\PromotionCategoryController@index');
          Route::name('admin.promotions_categories.create')->get('/adicionar', 'Promotions\PromotionCategoryController@create');
          Route::name('admin.promotions_categories.store')->post('/adicionar', 'Promotions\PromotionCategoryController@store');
          Route::name('admin.promotions_categories.edit')->get('/editar/{id}', 'Promotions\PromotionCategoryController@edit');
          Route::name('admin.promotions_categories.update')->put('/editar/{id}', 'Promotions\PromotionCategoryController@update');
          Route::name('admin.promotions_categories.destroy')->delete('/excluir/{id}', 'Promotions\PromotionCategoryController@destroy');
          Route::name('admin.promotions_categories.reorder')->post('/reordenar', 'Promotions\PromotionCategoryController@reorder');
        });
      });

      // Awards
      Route::prefix('premios')->group(function() {
        Route::name('admin.awards.index')->get('/', 'Awards\AwardController@index');
        Route::name('admin.awards.create')->get('/adicionar', 'Awards\AwardController@create');
        Route::name('admin.awards.store')->post('/adicionar', 'Awards\AwardController@store');
        Route::name('admin.awards.edit')->get('/editar/{id}', 'Awards\AwardController@edit');
        Route::name('admin.awards.update')->put('/editar/{id}', 'Awards\AwardController@update');
        Route::name('admin.awards.destroy')->delete('/excluir/{id}', 'Awards\AwardController@destroy');
        Route::name('admin.awards.reorder')->post('/reordenar', 'Awards\AwardController@reorder');

        Route::prefix('categorias')->group(function() {
          Route::name('admin.awards_categories.index')->get('/', 'Awards\AwardCategoryController@index');
          Route::name('admin.awards_categories.create')->get('/adicionar', 'Awards\AwardCategoryController@create');
          Route::name('admin.awards_categories.store')->post('/adicionar', 'Awards\AwardCategoryController@store');
          Route::name('admin.awards_categories.edit')->get('/editar/{id}', 'Awards\AwardCategoryController@edit');
          Route::name('admin.awards_categories.update')->put('/editar/{id}', 'Awards\AwardCategoryController@update');
          Route::name('admin.awards_categories.destroy')->delete('/excluir/{id}', 'Awards\AwardCategoryController@destroy');
          Route::name('admin.awards_categories.reorder')->post('/reordenar', 'Awards\AwardCategoryController@reorder');
        });
      });

      // Units
      Route::prefix('unidades')->group(function() {
        Route::name('admin.units.index')->get('/', 'Units\UnitController@index');
        Route::name('admin.units.create')->get('/adicionar', 'Units\UnitController@create');
        Route::name('admin.units.store')->post('/adicionar', 'Units\UnitController@store');
        Route::name('admin.units.edit')->get('/editar/{id}', 'Units\UnitController@edit');
        Route::name('admin.units.update')->put('/editar/{id}', 'Units\UnitController@update');
        Route::name('admin.units.destroy')->delete('/excluir/{id}', 'Units\UnitController@destroy');
      });

      // Permissions
      Route::prefix('permissoes')->group(function() {
        Route::name('admin.permissions.index')->get('/', 'Users\PermissionController@index');
        Route::name('admin.permissions.create')->get('/adicionar', 'Users\PermissionController@create');
        Route::name('admin.permissions.store')->post('/adicionar', 'Users\PermissionController@store');
        Route::name('admin.permissions.edit')->get('/editar/{id}', 'Users\PermissionController@edit');
        Route::name('admin.permissions.update')->put('/editar/{id}', 'Users\PermissionController@update');
        Route::name('admin.permissions.destroy')->delete('/excluir/{id}', 'Users\PermissionController@destroy');
      });

      // Roles
      Route::prefix('grupos')->group(function() {
        Route::name('admin.roles.index')->get('/', 'Users\RoleController@index');
        Route::name('admin.roles.create')->get('/adicionar', 'Users\RoleController@create');
        Route::name('admin.roles.store')->post('/adicionar', 'Users\RoleController@store');
        Route::name('admin.roles.edit')->get('/editar/{id}', 'Users\RoleController@edit');
        Route::name('admin.roles.update')->put('/editar/{id}', 'Users\RoleController@update');
      });

      // Users
      Route::prefix('usuarios')->group(function() {
        Route::name('admin.users.index')->get('/', 'Users\UserController@index');
        Route::name('admin.users.create')->get('/adicionar', 'Users\UserController@create');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::name('home.index')->get('/', 'Front\HomeController@index');

app/Models/Core/Audit.php
<?php

namespace App\Models\Core;

use Illuminate\Database\Eloquent\Model;
use OwenIt\Auditing\Contracts\Audit as AuditContract;
use OwenIt\Auditing\Audit as AuditTrait;
use Carbon\Carbon;

class Audit extends Model implements AuditContract
{
  use AuditTrait;

  protected $guarded = [];

  protected $casts = [
    'old_values' => 'json',
    'new_values' => 'json'
  ];

  /**
   * Scopes
  */
  public function scopeToday($query)
  {
    $query->whereDate('created_at', Carbon::today());
  }

  /**
   * Accesors
   */
  public function getTypeNameAttribute()
  {
    $auditableType = class_basename($this->auditable_type);

    // Get types
    $types = config('panel.audit.types');

    // Return type name
    return isset($types[$auditableType]) ? $types[$auditableType] : 'Indefinido';
  }

  public function getActionNameAttribute()
  {
    // Get actions
    $actions = config('panel.audit.actions');

    // Return action name
    return $actions[$this->event];
  }
}

app/Http/Controllers/Admin/Users/AccountController.php
<?php

namespace App\Http\Controllers\Admin\Users;

use App\Http\Controllers\Admin\BaseController;
use Illuminate\Http\Request;
use Artesaos\SEOTools\Traits\SEOTools as SEOToolsTrait;
use Auth;
use App\Models\Core\Audit;

class AccountController extends BaseController
{
  use SEOToolsTrait;

  private $audits;

  public function __construct(Audit $audits)
  {
    // Dependency Injection
    $this->audits = $audits;
  }

  /**
   * Show the specified resource.
   * @return Response
   */
  public function show()
  {
    // Get current user
    $result = Auth::guard('dashboard')->user();

    // Audits
    $results = $this->audits->where('user_id', $result->id)->paginate(5);

    // Set meta tags
    $this->seo()->setTitle('Perfil');

    // Return view
    return view('admin.accounts.show', compact('result', 'results'));
  }

  /**
   * Show the form for editing the specified resource.
   * @return Response
   */
  public function edit()
  {
    // Get current user
    $result = Auth::guard('dashboard')->user();

    // Set meta tags
    $this->seo()->setTitle('Editar Perfil');

    // Return view
    return view('admin.accounts.edit', compact('result'));
  }

  /**
   * Update the specified resource in storage.
   * @param  Request $request
   * @return Response
   */
  public function update(Request $request)
  {
    // Fetch current user
    $user = Auth::guard('dashboard')->user();

    $this->validate($request, [
      'first_name' => 'required|max:255',
      'last_name' => 'nullable|max:255',
      'email' => "required|email|unique:users,email,{$user->id}",
      'phone' => 'nullable|phone:BR',
      'password' => 'nullable|min:8|confirmed',
      'password_confirmation' => 'required_with:password',
      'photo' => 'nullable|image|max:1000'
    ]);

    // Fill data
    $user->fill($request->except('password', 'password_confirmation', 'photo'));

    // Check password is present
    if($request->filled('password')):
      $user->password = bcrypt($request->get('password'));
    endif;

    // Request photo
    $photo = $request->file('photo');

    // Upload photo if send
    if ($photo):
      $user->clearMediaCollection('user');
      $filename = md5($photo->getClientOriginalName()) . '.' . $photo->getClientOriginalExtension();
      $user->addMedia($photo)->usingName($user->first_name)->usingFileName($filename)->toMediaCollection('user');
    endif;

    // Save user
    $user->save();

    // Success message
    flash('Perfil atualizado com sucesso.')->success();

    // Redirect to profile
    return redirect()->route('admin.accounts.show');
  }
}

resources/views/admin/accounts/_form.blade.php
<div class="col-xl-8 col-lg-8 col-md-8 col-sm-12 grid-margin">
  <div class="card review-card bottom">
    <div class="card-header header-sm d-flex justify-content-between align-items-center">
      <h4 class="card-title"> <i class="link-icon mdi mdi-account"></i> Dados pessoais</h4>
    </div>
    <div class="card-body">
      <div class="row">
        <div class="form-group col-md-6 col-lg-6 col-sm-12">
          {!! Form::label('first_name', 'Nome', []) !!}
          {!! Form::text('first_name', old('first_name'), ['class' => 'form-control form-control-lg']) !!}
          @if($errors->has('first_name'))
            <span class="help-block">{{ $errors->first('first_name') }}</span>
          @endif
        </div>
        <div class="form-group col-md-6 col-lg-6 col-sm-12">
          {!! Form::label('last_name', 'Sobrenome', []) !!}
          {!! Form::text('last_name', old('last_name'), ['class' => 'form-control form-control-lg']) !!}
          @if($errors->has('last_name'))
            <span class="help-block">{{ $errors->first('last_name') }}</span>
          @endif
        </div>
        @if(isset($result))
        <div class="form-group col-md-6 col-lg-6 col-sm-12">
          {!! Form::label('password', 'Senha', []) !!}
          {!! Form::password('password', ['class' => 'form-control form-control-lg']) !!}

          @if($errors->has('password'))
          <span class="help-block">{{ $errors->first('password') }}</span>
          @endif
        </div>
        <div class="form-group col-md-6 col-lg-6 col-sm-12">
          {!! Form::label('password_confirmation', 'Confirmar senha', []) !!}
          {!! Form::password('password_confirmation', ['class' => 'form-control form-control-lg']) !!}

          @if($errors->has('password_confirmation'))
          <span class="help-block">{{ $errors->first('password_confirmation') }}</span>
          @endif
        </div>
        @endif
      </div>
    </div>
  </div>

  <div class="card review-card">
    <div class="card-header header-sm d-flex justify-content-between align-items-center">
      <h4 class="card-title"> <i class="link-icon mdi mdi-email-outline"></i> Contatos</h4>
    </div>
    <div class="card-body">
      <div class="row">
        <div class="form-group col-md-6 col-lg-6 col-sm-12">
          {!! Form::label('email', 'E-mail', []) !!}
          {!! Form::email('email', old('email'), ['class' => 'form-control form-control-lg']) !!}
          @if($errors->has('email'))
            <span class="help-block">{{ $errors->first('email') }}</span>
          @endif
        </div>
        <div class="form-group col-md-6 col-lg-6 col-sm-12">
          {!! Form::label('phone', 'Telefone', []) !!}
          {!! Form::text('phone', old('phone'), ['class' => 'form-control form-control-lg js-mask-phone']) !!}
          @if($errors->has('phone'))
            <span class="help-block">{{ $errors->first('phone') }}</span>
          @endif
        </div>
      </div>
    </div>
  </div>
</div>

<div class="col-xl-4 col-lg-4 col-md-4 col-sm-12">
  <div class="card review-card bottom">
    <div class="card-header header-sm d-flex justify-content-between align-items-center red">
      <h4 class="card-title"> <i class="icon-sm link-icon mdi mdi-camera"></i> Medias</h4>
    </div>
    <div class="card-body">
      <div class="row">
        <div class="form-group col-sm-12 col-lg-12 col-md-12">
          {!! Form::label('photo', 'Foto', ['']) !!}
          {!! Form::file('photo', ['class' => 'file-upload-default']) !!}
          <div class="input-group col-xs-12">
            <input type="text" class="form-control file-upload-info" disabled="" placeholder="">
            <span class="input-group-append">
              <button class="file-upload-browse btn btn-default" type="button">Selecionar</button>
            </span>
          </div>
          @if($errors->has('photo'))
            <span class="help-block">{{ $errors->first('photo') }}</span>
          @endif
        </div>
      </div>
    </div>
  </div>
</div>

resources/views/admin/accounts/edit.blade.php
@extends('admin.layouts.default')

@section('content')
  <div class="content-wrapper">
    @include('flash::message')
    {!! Form::model($result, ['route' => ['admin.accounts.update', 'id' => $result->id], 'method' => 'PUT', 'novalidate', 'role' => 'form', 'files' => true]) !!}
      <div class="row">
        {{ Breadcrumbs::render('accounts.edit', $result) }}
        <div class="col-md-12 d-flex align-items-stretch grid-margin">
          <div class="row flex-grow">
            <div class="col-12">
              <div class="card">
                <div class="card-body reset-padding margin-1">
                  <div class="card-action-title">
                    <h3> Editar Perfil
                      <small class="text-muted"> Preencha os campos abaixo. </small>
                    </h3>
                  </div>
                  <div class="card-actions">
                    <div class="margin-btn">
                      <a href="{{ route('admin.accounts.show') }}" class="btn btn-danger btn-lg" title="Voltar"><i class="fa fa-angle-left"></i>Voltar</a>
                    </div>
                    <div class="">
                      <button type="submit" class="btn btn-success btn-lg"><i class="fa fa-save"></i>Salvar</button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
       @include('admin.accounts._form')
      </div>
    {!! Form::close() !!}
  </div>
@endsection

resources/views/admin/accounts/show.blade.php
@extends('admin.layouts.default')

@section('content')
  <div class="content-wrapper">
    @include('flash::message')
    <div class="row">
      {{ Breadcrumbs::render('accounts.show') }}
    </div>
    <div class="row">
      <div class="col-md-12 d-flex align-items-stretch grid-margin">
        <div class="row flex-grow">
          <div class="col-12">
            <div class="card">
              <div class="card-body reset-padding margin-1">
                <div class="card-action-title">
                  <h3> Meu Perfil
                  </h3>
                </div>
                <div class="card-actions">
                  <div class="margin-btn">
                    <a href="{{ route('admin.dashboard.index') }}" class="btn btn-danger btn-lg" title="Voltar"><i class="fa fa-angle-left"></i>Voltar</a>
                  </div>
                  <div class="">
                    <a href="{{ route('admin.accounts.edit', ['id' => $result->id]) }}" class="btn btn-warning btn-lg"><i class="fa fa-pencil"></i>Editar</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-xl-4 col-lg-4 col-md-4 col-sm-12">
        <div class="card card-statistics social-card card-default">
          <div class="card-header header-sm">
            <div class="d-flex align-items-center">
              <div class="wrapper d-flex align-items-center media-info text-facebook">
                <i class="mdi mdi-account-circle icon-md"></i>
                <h2 class="card-title ml-3">Contato</h2>
              </div>
            </div>
          </div>
          <div class="card-body">
            <img class="d-block img-sm rounded-circle mx-auto mb-2" src="{{ $result->photo }}" alt="{{ $result->name }}">
            <p class="text-center user-name">{{ $result->full_name }}</p>
            <p class="text-center mb-2 comment">{{ $result->email }}</p>
            <small class="d-block mt-4 text-center posted-date">{{ $result->created_at->format('d/m/Y H:i') }}</small>
          </div>
          <div class="card-footer"></div>
        </div>
      </div>
      <div class="col-xl-8 col-lg-8 col-md-8 col-sm-12 grid-margin stretch-card">
        <div class="card card-statistics social-card card-default">
          <div class="card-header header-sm">
            <div class="d-flex align-items-center">
              <div class="wrapper d-flex align-items-center media-info text-facebook">
                <i class="mdi mdi-star-outline icon-md"></i>
                <h2 class="card-title ml-3">Atividades recentes</h2>
              </div>
            </div>
          </div>
          <div class="card-body">
            <table class="table table-striped">
              <thead>
                <tr>
                  <th> Usuário </th>
                  <th> Tipo </th>
                  <th> Ação </th>
                  <th> Horário </th>
                  <th> Ações </th>
                </tr>
              </thead>
              <tbody>
                @foreach($results as $result)
                  <tr>
                    <td> {{ $result->user->full_name }} </td>
                    <td> {{ $result->type_name }} </td>
                    <td> {{ $result->action_name }} </td>
                    <td> {{ $result->created_at->format('d/m/Y H:i') }} </td>
                    <td>
                      <a href="{{ route('admin.audits.show', ['id' => $result->id]) }}" class="action-icon -success" data-toggle="tooltip" data-placement="bottom" title="Visualizar" data-original-title="Visualizar"><i class="icon-eye"></i></a>
                    </td>
                  </tr>
                @endforeach
              </tbody>
            </table>
          </div>
          @include('admin.partials.pagination')
        </div>
      </div>
    </div>
  </div>
@endsection