routes/admin.php
<?php

/**
 * Admin Routes
 */
Route::prefix('admin')->group(function(){

  /**
  * Public Routes
  */
  Route::middleware('guest.admin')->group(function(){
    // Login
    Route::name('admin.session.login')->get('/acessar', 'Admin\Session\SessionController@showLoginForm');
    Route::name('admin.session.login')->post('/acessar', 'Admin\Session\SessionController@login');
    Route::name('autologin')->get('/autologin/{token}', '\Watson\Autologin\AutologinController@autologin');

    // Social Login
    Route::name('admin.social.redirect')->get('/social/redirect/{provider}', 'Admin\Session\SocialController@redirectToProvider');
    Route::name('admin.social.handle')->get('/social/handle/{provider}', 'Admin\Session\SocialController@handleProviderCallback');

    // Reset Password
    Route::name('admin.password.forgot')->get('/esqueci-minha-senha', 'Admin\Session\ForgotPasswordController@showLinkRequestForm');
    Route::name('admin.password.processForgot')->post('/esqueci-minha-senha', 'Admin\Session\ForgotPasswordController@sendResetLinkEmail');
    Route::name('admin.password.reset')->get('/cadastrar-senha/{token}', 'Admin\Session\ResetPasswordController@showResetForm');
    Route::name('admin.password.processReset')->post('/cadastrar-senha', 'Admin\Session\ResetPasswordController@reset');
  });

  // First access
  Route::name('admin.activation.create')->get('/primeiro-acesso', 'Admin\Session\ActivationController@showActivationForm');
  Route::name('admin.activation.processCreate')->post('/primeiro-acesso', 'Admin\Session\ActivationController@store');

  // Clients
  Route::name('admin.clients.welcome')->get('/bem-vindo/{id}', 'Admin\Clients\ClientController@welcome');

  /**
  * Protected Routes
  */
  Route::middleware(['auth.admin'])->group(function(){

    // Api Routes
    Route::prefix('api')->group(function(){
      // Media
      Route::prefix('media/images')->group(function(){
        Route::name('admin.media.index')->get('/', 'Api\MediaLibrary\MediaLibraryController@index');
        Route::name('admin.media.store')->post('/adicionar', 'Api\MediaLibrary\MediaLibraryController@store');
      });
    });

    // Logout
    Route::name('admin.session.logout')->get('/sair', 'Admin\Session\SessionController@logout');

    // Check first access
    Route::middleware(['first.access'])->namespace('Admin')->group(function() {

      // Dashboard
      Route::name('admin.dashboard.index')->get('/', 'Dashboard\DashboardController@index');

      // Account
      Route::prefix('perfil')->group(function() {
        Route::name('admin.accounts.show')->get('/', 'Users\AccountController@show');
        Route::name('admin.accounts.edit')->get('/atualizar', 'Users\AccountController@edit');
        Route::name('admin.accounts.update')->put('/atualizar', 'Users\AccountController@update');
      });

      // Orders
      Route::prefix('pedidos')->middleware('cors')->group(function() {
        Route::name('admin.orders.index')->get('/', 'Orders\OrderController@index');
      });

      // Releases
      Route::prefix('destaques')->group(function() {
        Route::name('admin.releases.index')->get('/', 'Releases\ReleaseController@index');
        Route::name('admin.releases.create')->get('/adicionar', 'Releases\ReleaseController@create');
        Route::name('admin.releases.store')->post('/adicionar', 'Releases\ReleaseController@store');
        Route::name('admin.releases.edit')->get('/editar/{id}', 'Releases\ReleaseController@edit');
        Route::name('admin.releases.update')->put('/editar/{id}', 'Releases\ReleaseController@update');
      });

      // Clients
      Route::prefix('clientes')->group(function() {
        Route::name('admin.clients.index')->get('/', 'Clients\ClientController@index');
        Route::name('admin.clients.show')->get('/visualizar/{id}', 'Clients\ClientController@show');
        Route::name('admin.clients.create')->get('/adicionar', 'Clients\ClientController@create');
        Route::name('admin.clients.store')->post('/adicionar', 'Clients\ClientController@store');
        Route::name('admin.clients.edit')->get('/editar/{id}', 'Clients\ClientController@edit');
        Route::name('admin.clients.update')->put('/editar/{id}', 'Clients\ClientController@update');
        Route::name('admin.clients.destroy')->delete('/deltar/{id}', 'Clients\ClientController@destroy');
      });

      // Promotions
      Route::prefix('promocoes')->group(function() {
        Route::name('admin.promotions.index')->get('/', 'Promotions\PromotionController@index');
        Route::name('admin.promotions.create')->get('/adicionar', 'Promotions\PromotionController@create');
        Route::name('admin.promotions.store')->post('/adicionar', 'Promotions\PromotionController@store');
        Route::name('admin.promotions.edit')->get('/editar/{id}', 'Promotions\PromotionController@edit');
        Route::name('admin.promotions.update')->put('/editar/{id}', 'Promotions\PromotionController@update');
        Route::name('admin.promotions.destroy')->delete('/excluir/{id}', 'Promotions\PromotionController@destroy');
        Route::name('admin.promotions.reorder')->post('/reordenar', 'Promotions\PromotionController@reorder');

        Route::prefix('categorias')->group(function() {
          Route::name('admin.promotions_categories.index')->get('/', 'Promotions\PromotionCategoryController@index');
          Route::name('admin.promotions_categories.create')->get('/adicionar', 'Promotions\PromotionCategoryController@create');
          Route::name('admin.promotions_categories.store')->post('/adicionar', 'Promotions\PromotionCategoryController@store');
          Route::name('admin.promotions_categories.edit')->get('/editar/{id}', 'Promotions\PromotionCategoryController@edit');
          Route::name('admin.promotions_categories.update')->put('/editar/{id}', 'Promotions\PromotionCategoryController@update');
          Route::name('admin.promotions_categories.destroy')->delete('/excluir/{id}', 'Promotions\PromotionCategoryController@destroy');
          Route::name('admin.promotions_categories.reorder')->post('/reordenar', 'Promotions\PromotionCategoryController@reorder');
        });
      });

      // Awards
      Route::prefix('premios')->group(function() {
        Route::name('admin.awards.index')->get('/', 'Awards\AwardController@index');
        Route::name('admin.awards.create')->get('/adicionar', 'Awards\AwardController@create');
        Route::name('admin.awards.store')->post('/adicionar', 'Awards\AwardController@store');
        Route::name('admin.awards.edit')->get('/editar/{id}', 'Awards\AwardController@edit');
        Route::name('admin.awards.update')->put('/editar/{id}', 'Awards\AwardController@update');
        Route::name('admin.awards.destroy')->delete('/excluir/{id}', 'Awards\AwardController@destroy');
        Route::name('admin.awards.reorder')->post('/reordenar', 'Awards\AwardController@reorder');

        Route::prefix('categorias')->group(function() {
          Route::name('admin.awards_categories.index')->get('/', 'Awards\AwardCategoryController@index');
          Route::name('admin.awards_categories.create')->get('/adicionar', 'Awards\AwardCategoryController@create');
          Route::name('admin.awards_categories.store')->post('/adicionar', 'Awards\AwardCategoryController@store');
          Route::name('admin.awards_categories.edit')->get('/editar/{id}', 'Awards\AwardCategoryController@edit');
          Route::name('admin.awards_categories.update')->put('/editar/{id}', 'Awards\AwardCategoryController@update');
          Route::name('admin.awards_categories.destroy')->delete('/excluir/{id}', 'Awards\AwardCategoryController@destroy');
          Route::name('admin.awards_categories.reorder')->post('/reordenar', 'Awards\AwardCategoryController@reorder');
        });
      });

      // Units
      Route::prefix('unidades')->group(function() {
        Route::name('admin.units.index')->get('/', 'Units\UnitController@index');
        Route::name('admin.units.create')->get('/adicionar', 'Units\UnitController@create');
        Route::name('admin.units.store')->post('/adicionar', 'Units\UnitController@store');
        Route::name('admin.units.edit')->get('/editar/{id}', 'Units\UnitController@edit');
        Route::name('admin.units.update')->put('/editar/{id}', 'Units\UnitController@update');
        Route::name('admin.units.destroy')->delete('/excluir/{id}', 'Units\UnitController@destroy');
      });

      // Permissions
      Route::prefix('permissoes')->group(function() {
        Route::name('admin.permissions.index')->get('/', 'Users\PermissionController@index');
        Route::name('admin.permissions.create')->get('/adicionar', 'Users\PermissionController@create');
        Route::name('admin.permissions.store')->post('/adicionar', 'Users\PermissionController@store');
        Route::name('admin.permissions.edit')->get('/editar/{id}', 'Users\PermissionController@edit');
        Route::name('admin.permissions.update')->put('/editar/{id}', 'Users\PermissionController@update');
        Route::name('admin.permissions.destroy')->delete('/excluir/{id}', 'Users\PermissionController@destroy');
      });

      // Roles
      Route::prefix('grupos')->group(function() {
        Route::name('admin.roles.index')->get('/', 'Users\RoleController@index');
        Route::name('admin.roles.create')->get('/adicionar', 'Users\RoleController@create');
        Route::name('admin.roles.store')->post('/adicionar', 'Users\RoleController@store');
        Route::name('admin.roles.edit')->get('/editar/{id}', 'Users\RoleController@edit');
        Route::name('admin.roles.update')->put('/editar/{id}', 'Users\RoleController@update');
      });

      // Users
      Route::prefix('usuarios')->group(function() {
        Route::name('admin.users.index')->get('/', 'Users\UserController@index');
        Route::name('admin.users.create')->get('/adicionar', 'Users\UserController@create');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::name('home.index')->get('/', 'Front\HomeController@index');

app/Models/Client/Client.php
<?php

namespace App\Models\Client;

use Spatie\MediaLibrary\Models\Media;
use Spatie\MediaLibrary\HasMedia\HasMedia;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;
use Spatie\Image\Manipulations;
use Illuminate\Notifications\Notifiable;
use Carbon\Carbon;
use Cviebrock\EloquentSluggable\Sluggable;
use App\Models\Auth\User;
use App\Models\Unit\Unit;
use App\Models\Award\Award;
use OwenIt\Auditing\Contracts\Auditable as AuditableInterface;
use OwenIt\Auditing\Auditable as AuditableTrait;
use Illuminate\Database\Eloquent\Model;
use Tymon\JWTAuth\Contracts\JWTSubject;
use Illuminate\Foundation\Auth\User as Authenticatable;
use App\Notifications\Clients\Welcome;

class Client extends Authenticatable implements JWTSubject, HasMedia, AuditableInterface
{
  use AuditableTrait, Sluggable, HasMediaTrait, Notifiable;

  protected $guard_name = 'clients';

  protected $fillable = [
    'slug',
    'first_name',
    'last_name',
    'phone',
    'sexo',
    'email',
    'cpf',
    'cash_total',
    'salt_points',
    'birthday',
    'password',
    'receive_messages',
    'termUse',
    'address_id',
    'user_id',
    'active'
  ];

  protected $hidden = [
    'password',
    'remember_token'
  ];

  protected $casts = [
    'receive_messages' => 'boolean',
    'termUse' => 'boolean',
    'active' => 'boolean'
  ];

  protected $dates = [
    'birthday'
  ];

  /**
   * Auditable Config
   */
  protected $auditInclude = [
    'slug',
    'first_name',
    'last_name',
    'phone',
    'sexo',
    'email',
    'cpf',
    'cash_total',
    'salt_points',
    'birthday',
    'password',
    'receive_messages',
    'termUse',
    'address_id',
    'user_id',
    'active'
  ];

  /**
  * Return the sluggable configuration array for this model.
  *
  * @return array
  */
  public function sluggable()
  {
    return [
      'slug' => [
        'source' => 'full_name'
      ]
    ];
  }

  /**
   * MediaLibrary Config
   */
  public function registerMediaConversions(Media $media = null)
  {
    $this->addMediaConversion('client_photo')
         ->fit(Manipulations::FIT_CROP, 320, 320)
         ->quality(90)
         ->nonQueued();
  }

  /**
  * Scopes
  */
  public function scopebyActive($query)
  {
    return $query->where('active', true);
  }

  /**
  * Notifications
  */
  public function sendWelcomeNotification($client)
  {
    $this->notify(new Welcome($client));
  }

  /**
   * Relationships
  */
  public function creator()
  {
    return $this->belongsTo(User::class, 'user_id');
  }

  public function address()
  {
    return $this->belongsTo(ClientAddress::class, 'address_id');
  }

  public function awards()
  {
    return $this->belongsToMany(Award::class, 'clients_awards')->withPivot(['active', 'points']);
  }

  /**
  * Mutators
  */
  public function setEmailAttribute($input)
  {
    if ($input)
      $this->attributes['email'] = mb_strtolower($input, 'UTF-8');
  }

  public function setPhoneAttribute($input)
  {
    if ($input)
      $this->attributes['phone'] = trim(preg_replace('#[^0-9]#', '', $input));
  }

  public function setBirthdayAttribute($input)
  {
    if($input)
      $this->attributes['birthday'] = Carbon::createFromFormat('d/m/Y', $input)->format('Y-m-d');
  }

  public function setPasswordAttribute($password)
  {
    $this->attributes['password'] = bcrypt($password);
  }

  public function setCpfAttribute($value)
  {
    $this->attributes['cpf'] = ($value != null) ? trim(preg_replace('#[^0-9]#', '', $value)) : null;
  }

  public function setCashTotalAttribute($value)
  {
    $this->attributes['cash_total'] = ($value != null) ? str_replace(['.', ','], ['', '.'], $value) : null;
  }

  /**
  * Accesors
  */
  public function getPhotoAttribute()
  {
    $image = $this->getMedia('client_photo')->first();
    return isset($image) ? $image->getFullUrl() : asset('/assets/images/faces/default.png');
  }

  public function getFullNameAttribute()
  {
    return "{$this->first_name} {$this->last_name}";
  }

  public function getRefPointsAttribute()
  {
    return str_pad($this->salt_points, 0, STR_PAD_LEFT) . "P";
  }

	public function getBirthdayFormatedAttribute()
	{
		return $this->birthday;
	}

  public function subtractPoints($awards_points)
  {
    return $diff = (int) $this->salt_points - (int) $awards_points;
  }

  public function checkPoints($awards_points)
  {
    if ( (int) $this->salt_points >= (int) $awards_points)
      return true;

    return false;
  }

  /**
  * Get the identifier that will be stored in the subject claim of the JWT.
  *
  * @return mixed
  */
  public function getJWTIdentifier()
  {
    return $this->getKey();
  }

  /**
   * Return a key value array, containing any custom claims to be added to the JWT.
   *
   * @return array
   */
  public function getJWTCustomClaims()
  {
    return [];
  }
}

resources/views/admin/partials/banner.blade.php
<div class="hero-banner">
  <!-- partial:partials/_navbar.html -->
  <div class="navbar">
    <div class="container-wrapper-width">
      <div class="row w-100">
        <div class="col-2 col-md-4 navbar-col order-md-1">
          <a href="index.html" class="brand-logo">
            <img src="../assets/images/logo_6.svg" alt="logo">
          </a>
          <a href="index.html" class="brand-logo-mini">
            <img src="../assets/images/logo-mini_6.svg" alt="logo">
          </a>
        </div>
        <div class="d-none d-md-block col-md-4 navbar-col order-md-0">
          <ul class="nav">
            <li class="nav-item dropdown project-dropdown">
              <a class="nav-link dropdown-toggle pl-0" id="projectDropdown" href="#" data-toggle="dropdown" aria-expanded="false">
                <span class="title-text font-weight-bold ml-0">Unidades</span>
              </a>
              <div class="dropdown-menu dropdown-menu-left navbar-dropdown pb-0" aria-labelledby="projectDropdown">
                <a class="dropdown-item">
                  Torre
                  <i class="dropdown-item-icon mdi mdi-map-marker"></i>
                </a>
                <a class="dropdown-item">
                  Bessa
                  <i class="dropdown-item-icon mdi mdi-map-marker"></i>
                </a>
                <a class="dropdown-item">
                  Manaíra
                  <i class="dropdown-item-icon mdi mdi-map-marker"></i>
                </a>
                <a class="dropdown-item">
                  Todas
                  <i class="dropdown-item-icon mdi mdi-map-marker"></i>
                </a>
              </div>
            </li>
            <li class="nav-item">
              <a href="#" class="nav-link">
                <i class="mdi mdi-logout"></i>
                <span class="title-text">Sair</span>
              </a>
            </li>
          </ul>
        </div>
        <div class="col-10 col-md-4 navbar-col order-md-3">
          <ul class="nav navbar-nav-right ml-auto">
       {{--      <li class="nav-item">
              <a href="#" class="nav-link">
                <i class="mdi mdi-magnify"></i>
              </a>
            </li> --}}
            <li class="nav-item dropdown">
              <a class="nav-link count-indicator dropdown-toggle" id="messageDropdown" href="#" data-toggle="dropdown" aria-expanded="false">
                <i class="mdi mdi-settings-outline"></i>
                <span class="count bg-info"></span>
              </a>
              <div class="dropdown-menu dropdown-menu-right navbar-dropdown preview-list pb-0" aria-labelledby="messageDropdown">
                <a class="dropdown-item py-3 border-bottom">
                  <p class="mb-0 font-weight-medium float-left">You have 4 new notifications </p>
                  <span class="badge badge-pill badge-primary float-right">View all</span>
                </a>
                <a class="dropdown-item preview-item py-3">
                  <div class="preview-thumbnail">
                    <i class="mdi mdi-alert m-auto text-primary"></i>
                  </div>
                  <div class="preview-item-content">
                    <h6 class="preview-subject font-weight-normal text-dark mb-1">Application Error</h6>
                    <p class="font-weight-light small-text mb-0"> Just now </p>
                  </div>
                </a>
                <a class="dropdown-item preview-item py-3">
                  <div class="preview-thumbnail">
                    <i class="mdi mdi-settings m-auto text-primary"></i>
                  </div>
                  <div class="preview-item-content">
                    <h6 class="preview-subject font-weight-normal text-dark mb-1">Settings</h6>
                    <p class="font-weight-light small-text mb-0"> Private message </p>
                  </div>
                </a>
                <a class="dropdown-item preview-item py-3">
                  <div class="preview-thumbnail">
                    <i class="mdi mdi-airballoon m-auto text-primary"></i>
                  </div>
                  <div class="preview-item-content">
                    <h6 class="preview-subject font-weight-normal text-dark mb-1">New user registration</h6>
                    <p class="font-weight-light small-text mb-0"> 2 days ago </p>
                  </div>
                </a>
              </div>
            </li>
      {{--       <li class="nav-item dropdown">
              <a class="nav-link count-indicator dropdown-toggle" id="notificationDropdown" href="#" data-toggle="dropdown">
                <i class="mdi mdi-circle-slice-3"></i>
              </a>
              <div class="dropdown-menu dropdown-menu-right navbar-dropdown dropdown-h-style-1 pb-0" aria-labelledby="notificationDropdown">
                <a class="dropdown-item">Print Invoice<i class="dropdown-item-icon ti-printer"></i></a>
                <a class="dropdown-item">Copy<i class="dropdown-item-icon ti-files"></i></a>
                <a class="dropdown-item">CSV<i class="dropdown-item-icon ti-write"></i></a>
                <a class="dropdown-item">Share<i class="dropdown-item-icon ti-share"></i></a>
              </div>
            </li> --}}
            <li class="nav-item dropdown d-none d-xl-inline-block user-dropdown">
              <a class="nav-link dropdown-toggle" id="UserDropdown" href="#" data-toggle="dropdown" aria-expanded="false">
                <img class="img-xs rounded-circle" src="{{ auth()->user()->photo }}" alt="Profile image">
                <span class="profile-text">{{ auth()->user()->full_name }}</span>
              </a>
              <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="UserDropdown">
                <div class="dropdown-header text-center">
                  <img class="img-md rounded-circle" src="../assets/images/faces/face1.jpg" alt="Profile image">
                  <p class="mb-1 mt-3 font-weight-semibold">Allen Moreno</p>
                  <p class="font-weight-light text-muted mb-0">allenmoreno@gmail.com</p>
                </div>
                <a class="dropdown-item">My Profile <span class="badge badge-pill badge-danger">1</span><i class="dropdown-item-icon ti-dashboard"></i></a>
                <a class="dropdown-item">Messages<i class="dropdown-item-icon ti-comment-alt"></i></a>
                <a class="dropdown-item">Activity<i class="dropdown-item-icon ti-location-arrow"></i></a>
                <a class="dropdown-item">FAQ<i class="dropdown-item-icon ti-help-alt"></i></a>
                <a class="dropdown-item">Sign Out<i class="dropdown-item-icon ti-power-off"></i></a>
              </div>
            </li>
          </ul>
          <button class="navbar-toggler navbar-toggler-right d-md-none align-self-center" type="button">
            <span class="mdi mdi-menu"></span>
          </button>
          <button class="chat-toggler d-md-none align-self-center" type="button">
            <span class="mdi mdi-dots-vertical"></span>
          </button>
        </div>
      </div>
    </div>
  </div>
  <!-- partial -->
</div>

resources/views/admin/partials/breadcrumbs.blade.php
@if (count($breadcrumbs))
  <div class="col-md-12 col-lg-12 col-sm-12">
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb bg-primary">
        @foreach ($breadcrumbs as $breadcrumb)
          @if ($breadcrumb->url && !$loop->last)
            <li class="breadcrumb-item">
              <a href="{{ $breadcrumb->url }}" title="{{ $breadcrumb->title }}">{{ $breadcrumb->title }}</a>
            </li>
          @else
            <li class="breadcrumb-item active">
              <a href="#" title="{{ $breadcrumb->title }}">{{ $breadcrumb->title }}</a>
            </li>
          @endif
        @endforeach
      </ol>
    </nav>
  </div>
@endif

resources/views/admin/partials/favicons.blade.php
<link rel="apple-touch-icon" sizes="180x180" href="{{ asset('favicon.ico') }}">
<link rel="icon" type="image/png" sizes="32x32" href="{{ asset('favicon.ico') }}">
<link rel="icon" type="image/png" sizes="16x16" href="{{ asset('favicon.ico') }}">
<link rel="mask-icon" href="{{ asset('/assets/favicons/safari-pinned-tab.svg') }}" color="#f4c42a">
<link rel="manifest" href="{{ asset('/assets/favicons/manifest.json') }}">
<link rel="shortcut icon" href="{{ asset('favicon.ico') }}">
<meta name="msapplication-TileColor" content="#f4c42a">
<meta name="msapplication-config" content="{{ asset('/assets/favicons/browserconfig.xml') }}">
<meta name="theme-color" content="#f4c42a">

resources/views/admin/partials/footer.blade.php
<footer class="footer">
  <div class="container clearfix">
    <span class="text-muted d-block text-center text-sm-left d-sm-inline-block">Copyright © 2019
      <a href="{{ route('home.index') }}" target="_blank" title="{{ config('app.name') }} - Todos os direitos reservados.">{{ config('app.name') }}</a>. Todos os direitos reservados.</span>
    <span class="float-none float-sm-right d-block mt-1 mt-sm-0 text-center">Criado e mantido por {{ config('app.name') }}
    </span>
  </div>
</footer>

resources/views/admin/partials/navbar.blade.php
 <nav class="navbar horizontal-layout col-lg-12 col-12 p-0">
    <div class="container d-flex flex-row nav-top">
      <div class="text-center navbar-brand-wrapper d-flex align-items-top">
        <a class="navbar-brand brand-logo" href="{{ route('admin.dashboard.index') }}" title="Home">
          <img src="{{ asset('/assets/images/marca2.png') }}" alt="logo" /> </a>
        <a class="navbar-brand brand-logo-mini" href="{{ route('admin.dashboard.index') }}" title="Home">
          <img src="{{ asset('/assets/images/marca2.png') }}" alt="logo" /> </a>
      </div>
      <div class="navbar-menu-wrapper d-flex align-items-center">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item dropdown d-none d-xl-inline-block">
            <a class="nav-link dropdown-toggle" id="UserDropdown" href="#" data-toggle="dropdown" aria-expanded="false">Olá,
              {{ auth()->user()->first_name }}
              <img class="img-xs rounded-circle ml-3" src="{{ auth()->user()->photo }}" alt="Profile image"> </a>
            <div class="dropdown-menu dropdown-menu-right navbar-dropdown" aria-labelledby="UserDropdown">
              <a href="{{ route('admin.accounts.show') }}" class="dropdown-item mt-2" title="Perfil"> Perfil </a>
              <a href="{{ route('home.index') }}" target="_blank" class="dropdown-item mt-2" title="Ir ao site"> Ir ao site </a>
              <a href="{{ route('admin.session.logout') }}" class="dropdown-item" title="Sair"> Sair </a>
            </div>
          </li>
        </ul>
        <button class="navbar-toggler align-self-center" type="button" data-toggle="minimize">
          <span class="mdi mdi-menu"></span>
        </button>
      </div>
    </div>
    <div class="nav-bottom">
      <div class="container">
        <ul class="nav page-navigation">
          <li class="nav-item {{ active('admin.dashboard.index', 'active') }}">
            <a href="{{ route('admin.dashboard.index') }}" class="nav-link" title="Dashboard">
              <i class="link-icon mdi mdi-airplay"></i>
              <span class="menu-title">Dashboard</span>
            </a>
          </li>
          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="link-icon mdi mdi-chart-line"></i>
              <span class="menu-title">Relatórios</span>
            </a>
          </li>
          {{-- <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="link-icon mdi mdi-chart-line"></i>
              <span class="menu-title">Acessos</span>
            </a>
          </li> --}}
      {{--     <li class="nav-item {{ active(['admin.messages.index', 'admin.messages.show', 'admin.departments.index', 'admin.departments.create', 'admin.departments.edit'], 'active') }}">
            <a href="{{ route('admin.messages.index') }}" class="nav-link" title="Mensagens">
              <i class="link-icon mdi mdi-comment-outline"></i>
              <span class="menu-title">Mensagens</span>
            </a>
          </li> --}}
          <li class="nav-item {{ active('admin.audits.index', 'active') }}">
            <a href="{{ route('admin.audits.index') }}" class="nav-link" title="Auditoria">
              <i class="link-icon mdi mdi-equal-box"></i>
              <span class="menu-title">Auditoria</span>
            </a>
          </li>
          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="link-icon mdi mdi-cube-outline"></i>
              <span class="menu-title ">Módulos</span>
              <i class="menu-arrow "></i>
            </a>
            <div class="submenu">
              <ul class="submenu-item ">
                @foreach(config('panel.menu') as $menu)
                  @can($menu['permission'])
                  <li class="nav-item {{ active($menu['route'], 'active') }}">
                    <a class="nav-link" href="{{ route($menu['route']) }}" title="{{ $menu['name'] }}">{{ $menu['name'] }}</a>
                  </li>
                  @endcan
                @endforeach
              </ul>
            </div>
          </li>
        </ul>
      </div>
    </div>
  </nav>

resources/views/admin/partials/pagination.blade.php
<div class="card-footer">
  <div class="col-lg-12">
    <nav class="pull-right">
      <ul class="pagination rounded">
        {!! $results->render() !!}
      </ul>
    </nav>
  </div>
</div>